<?php

use Illuminate\Database\Seeder;

class OrderDetailsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0');
        \Illuminate\Support\Facades\DB::table('order_details')->truncate();
        \Illuminate\Support\Facades\DB::table('order_details')->insert([
            [
                'order_id'=>1,
                'product_id'=>2,
                'quantity'=>1,
                'unit_price'=>1750000
            ],
            [
                'order_id'=>2,
                'product_id'=>3,
                'quantity'=>1,
                'unit_price'=>790000
            ],
            [
                'order_id'=>3,
                'product_id'=>5,
                'quantity'=>1,
                'unit_price'=>2500000
            ],
            [
                'order_id'=>4,
                'product_id'=>6,
                'quantity'=>1,
                'unit_price'=>4000000
            ],
            [
                'order_id'=>5,
                'product_id'=>2,
                'quantity'=>1,
                'unit_price'=>5000000
            ],
            [
                'order_id'=>6,
                'product_id'=>3,
                'quantity'=>1,
                'unit_price'=>678000
            ],
            [
                'order_id'=>7,
                'product_id'=>2,
                'quantity'=>1,
                'unit_price'=>890000
            ],
            [
                'order_id'=>8,
                'product_id'=>2,
                'quantity'=>1,
                'unit_price'=>1270000
            ],
            [
                'order_id'=>9,
                'product_id'=>2,
                'quantity'=>1,
                'unit_price'=>1460000
            ],
            [
                'order_id'=>10,
                'product_id'=>2,
                'quantity'=>1,
                'unit_price'=>150000
            ],
            [
                'order_id'=>11,
                'product_id'=>13,
                'quantity'=>1,
                'unit_price'=>712000
            ],
            [
                'order_id'=>11,
                'product_id'=>17,
                'quantity'=>1,
                'unit_price'=>1312000
            ],
            [
                'order_id'=>12,
                'product_id'=>10,
                'quantity'=>1,
                'unit_price'=>612000
            ],
            [
                'order_id'=>12,
                'product_id'=>13,
                'quantity'=>1,
                'unit_price'=>712000
            ],
            [
                'order_id'=>12,
                'product_id'=>26,
                'quantity'=>1,
                'unit_price'=>391000
            ],
            [
                'order_id'=>12,
                'product_id'=>27,
                'quantity'=>1,
                'unit_price'=>225000
            ],
            [
                'order_id'=>12,
                'product_id'=>39,
                'quantity'=>1,
                'unit_price'=>632000
            ],
            [
                'order_id'=>13,
                'product_id'=>19,
                'quantity'=>1,
                'unit_price'=>700000
            ],
            [
                'order_id'=>13,
                'product_id'=>21,
                'quantity'=>1,
                'unit_price'=>1690000
            ],
            [
                'order_id'=>13,
                'product_id'=>24,
                'quantity'=>1,
                'unit_price'=>360000
            ],
            [
                'order_id'=>14,
                'product_id'=>5,
                'quantity'=>1,
                'unit_price'=>500000
            ],
            [
                'order_id'=>14,
                'product_id'=>10,
                'quantity'=>1,
                'unit_price'=>612000
            ],
            [
                'order_id'=>14,
                'product_id'=>39,
                'quantity'=>1,
                'unit_price'=>632000
            ],
            [
                'order_id'=>15,
                'product_id'=>6,
                'quantity'=>1,
                'unit_price'=>585000
            ],
            [
                'order_id'=>15,
                'product_id'=>15,
                'quantity'=>1,
                'unit_price'=>646000
            ],
            [
                'order_id'=>15,
                'product_id'=>28,
                'quantity'=>1,
                'unit_price'=>125000
            ],
            [
                'order_id'=>15,
                'product_id'=>35,
                'quantity'=>1,
                'unit_price'=>250000
            ],
            [
                'order_id'=>16,
                'product_id'=>3,
                'quantity'=>1,
                'unit_price'=>1850000
            ],
            [
                'order_id'=>16,
                'product_id'=>27,
                'quantity'=>1,
                'unit_price'=>225000
            ],
            [
                'order_id'=>16,
                'product_id'=>32,
                'quantity'=>1,
                'unit_price'=>600000
            ],
            [
                'order_id'=>16,
                'product_id'=>33,
                'quantity'=>1,
                'unit_price'=>351000
            ],
            [
                'order_id'=>16,
                'product_id'=>36,
                'quantity'=>1,
                'unit_price'=>390000
            ],
            [
                'order_id'=>17,
                'product_id'=>8,
                'quantity'=>1,
                'unit_price'=>550000
            ],
            [
                'order_id'=>17,
                'product_id'=>11,
                'quantity'=>1,
                'unit_price'=>790000
            ],
            [
                'order_id'=>17,
                'product_id'=>12,
                'quantity'=>1,
                'unit_price'=>430000
            ],
            [
                'order_id'=>17,
                'product_id'=>14,
                'quantity'=>1,
                'unit_price'=>750000
            ],
            [
                'order_id'=>17,
                'product_id'=>16,
                'quantity'=>1,
                'unit_price'=>1450000
            ],
            [
                'order_id'=>18,
                'product_id'=>28,
                'quantity'=>1,
                'unit_price'=>125000
            ],
            [
                'order_id'=>18,
                'product_id'=>39,
                'quantity'=>1,
                'unit_price'=>632000
            ],
            [
                'order_id'=>19,
                'product_id'=>2,
                'quantity'=>1,
                'unit_price'=>1275000
            ],
            [
                'order_id'=>19,
                'product_id'=>42,
                'quantity'=>1,
                'unit_price'=>1096500
            ],
            [
                'order_id'=>20,
                'product_id'=>22,
                'quantity'=>1,
                'unit_price'=>950000
            ],
            [
                'order_id'=>20,
                'product_id'=>23,
                'quantity'=>1,
                'unit_price'=>490000
            ],
            [
                'order_id'=>20,
                'product_id'=>24,
                'quantity'=>1,
                'unit_price'=>360000
            ],
            [
                'order_id'=>21,
                'product_id'=>15,
                'quantity'=>1,
                'unit_price'=>646000
            ],
            [
                'order_id'=>21,
                'product_id'=>33,
                'quantity'=>1,
                'unit_price'=>351000
            ],
            [
                'order_id'=>21,
                'product_id'=>42,
                'quantity'=>1,
                'unit_price'=>1096500
            ],
            [
                'order_id'=>22,
                'product_id'=>17,
                'quantity'=>1,
                'unit_price'=>1312000
            ],
            [
                'order_id'=>22,
                'product_id'=>25,
                'quantity'=>1,
                'unit_price'=>330000
            ],
            [
                'order_id'=>22,
                'product_id'=>24,
                'quantity'=>1,
                'unit_price'=>290000
            ],
            [
                'order_id'=>23,
                'product_id'=>11,
                'quantity'=>1,
                'unit_price'=>790000
            ],
            [
                'order_id'=>23,
                'product_id'=>13,
                'quantity'=>1,
                'unit_price'=>712000
            ],
            [
                'order_id'=>23,
                'product_id'=>14,
                'quantity'=>1,
                'unit_price'=>750000
            ],
            [
                'order_id'=>23,
                'product_id'=>27,
                'quantity'=>1,
                'unit_price'=>225000
            ],
            [
                'order_id'=>24,
                'product_id'=>26,
                'quantity'=>1,
                'unit_price'=>391000
            ],
            [
                'order_id'=>24,
                'product_id'=>30,
                'quantity'=>1,
                'unit_price'=>90000
            ],
            [
                'order_id'=>24,
                'product_id'=>43,
                'quantity'=>1,
                'unit_price'=>1900000
            ],
            [
                'order_id'=>25,
                'product_id'=>1,
                'quantity'=>1,
                'unit_price'=>1800000
            ],
            [
                'order_id'=>25,
                'product_id'=>2,
                'quantity'=>1,
                'unit_price'=>1275000
            ],
            [
                'order_id'=>25,
                'product_id'=>7,
                'quantity'=>1,
                'unit_price'=>750000
            ],
            [
                'order_id'=>26,
                'product_id'=>16,
                'quantity'=>1,
                'unit_price'=>1450000
            ],
            [
                'order_id'=>26,
                'product_id'=>18,
                'quantity'=>1,
                'unit_price'=>1230000
            ],
            [
                'order_id'=>26,
                'product_id'=>21,
                'quantity'=>1,
                'unit_price'=>1690000
            ],
            [
                'order_id'=>27,
                'product_id'=>9,
                'quantity'=>1,
                'unit_price'=>850000
            ],
            [
                'order_id'=>27,
                'product_id'=>32,
                'quantity'=>1,
                'unit_price'=>600000
            ],
            [
                'order_id'=>27,
                'product_id'=>36,
                'quantity'=>1,
                'unit_price'=>390000
            ],
            [
                'order_id'=>28,
                'product_id'=>13,
                'quantity'=>1,
                'unit_price'=>712000
            ],
            [
                'order_id'=>29,
                'product_id'=>7,
                'quantity'=>1,
                'unit_price'=>750000
            ],
            [
                'order_id'=>30,
                'product_id'=>10,
                'quantity'=>1,
                'unit_price'=>612000
            ],
            [
                'order_id'=>31,
                'product_id'=>20,
                'quantity'=>1,
                'unit_price'=>630000
            ],
            [
                'order_id'=>32,
                'product_id'=>12,
                'quantity'=>1,
                'unit_price'=>430000
            ],
            [
                'order_id'=>33,
                'product_id'=>21,
                'quantity'=>1,
                'unit_price'=>1690000
            ],
            [
                'order_id'=>34,
                'product_id'=>2,
                'quantity'=>1,
                'unit_price'=>1275000
            ],
            [
                'order_id'=>35,
                'product_id'=>18,
                'quantity'=>1,
                'unit_price'=>1230000
            ],
            [
                'order_id'=>36,
                'product_id'=>17,
                'quantity'=>1,
                'unit_price'=>1312000
            ],
            [
                'order_id'=>37,
                'product_id'=>6,
                'quantity'=>1,
                'unit_price'=>585000
            ],
            [
                'order_id'=>38,
                'product_id'=>30,
                'quantity'=>1,
                'unit_price'=>90000
            ],
            [
                'order_id'=>38,
                'product_id'=>35,
                'quantity'=>1,
                'unit_price'=>250000
            ],
            [
                'order_id'=>39,
                'product_id'=>16,
                'quantity'=>1,
                'unit_price'=>1450000
            ],
            [
                'order_id'=>40,
                'product_id'=>11,
                'quantity'=>1,
                'unit_price'=>790000
            ],
            [
                'order_id'=>41,
                'product_id'=>7,
                'quantity'=>1,
                'unit_price'=>750000
            ],
            [
                'order_id'=>42,
                'product_id'=>23,
                'quantity'=>1,
                'unit_price'=>490000
            ],
            [
                'order_id'=>42,
                'product_id'=>24,
                'quantity'=>1,
                'unit_price'=>360000
            ],
            [
                'order_id'=>43,
                'product_id'=>22,
                'quantity'=>1,
                'unit_price'=>950000
            ],
            [
                'order_id'=>44,
                'product_id'=>38,
                'quantity'=>1,
                'unit_price'=>935000
            ],
            [
                'order_id'=>45,
                'product_id'=>37,
                'quantity'=>3,
                'unit_price'=>890000
            ],
            [
                'order_id'=>45,
                'product_id'=>40,
                'quantity'=>3,
                'unit_price'=>1690000
            ],
            [
                'order_id'=>46,
                'product_id'=>38,
                'quantity'=>5,
                'unit_price'=>935000
            ],
            [
                'order_id'=>46,
                'product_id'=>41,
                'quantity'=>5,
                'unit_price'=>390000
            ],
            [
                'order_id'=>47,
                'product_id'=>4,
                'quantity'=>5,
                'unit_price'=>1100000
            ],
            [
                'order_id'=>48,
                'product_id'=>1,
                'quantity'=>3,
                'unit_price'=>1800000
            ],
            [
                'order_id'=>49,
                'product_id'=>3,
                'quantity'=>2,
                'unit_price'=>1850000
            ],
            [
                'order_id'=>50,
                'product_id'=>29,
                'quantity'=>2,
                'unit_price'=>350000
            ],
        ]);
    }
}
